services:
  devroutine.api:
    image: devroutine.api
    build:
      context: .
      dockerfile: DevRoutine/DevRoutine.Api/Dockerfile
    ports:
      - "5010:8080"
      - "5011:8081"
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devroutine.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devroutine.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  
  dev_routine.postgres:
    image: postgres:17.2 # or latest
    environment:
      POSTGRES_DB: dev_routine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  
  devroutine.seq:
    image: datalust/seq:2024.3 # or latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - "8080:80"
      - "5341:5341"

  devroutine.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888"